#!/usr/bin/env ruby

require 'fileutils'
require 'open-uri'

git_bundles = [
  "git://github.com/zsh-users/zsh-syntax-highlighting.git"
]

FileUtils.cd File.dirname(__FILE__)

def install_syntax_highlighting(bundles)
  git_bundles = bundles
  git_bundles.each do |url|
    dir = url.split('/').last.sub(/\.git$/, '')

    if File.exists?(dir)
      puts "  Pulling from #{url} into #{dir}"
      `cd #{dir} && git reset --hard && git pull && cd ..`
    else
      puts "  Unpacking #{url} into #{dir}"
      `git clone #{url} #{dir}`
    end
  end
end

def link_zshrc
  `ln -s ~/.zsh/.zshrc ~/.zshrc`
end

link_zshrc
install_syntax_highlighting git_bundles

