#!/usr/bin/env ruby

require 'fileutils'
require 'open-uri'

git_bundles = [
  "git://github.com/zsh-users/zsh-syntax-highlighting.git"
]

FileUtils.cd File.dirname(__FILE__)

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')

  if File.exists?(dir)
    puts "  Pulling from #{url} into #{dir}"
    `cd #{dir} && git reset --hard && git pull && cd ..`
  else
    puts "  Unpacking #{url} into #{dir}"
    `git clone #{url} #{dir}`
  end
end

puts "done with zsh-syntax-highlighting"
